#!/usr/bin/env python
"""
Get largest SOL accounts.

Generated by generate_isolated_scripts.py.
This file is intentionally standalone and loads .env by itself.
"""
import json
import os
from pathlib import Path

import base58
import requests
from solana.rpc.api import Client
from solders.keypair import Keypair
from solders.pubkey import Pubkey


def load_dotenv() -> None:
    search_roots = [Path.cwd(), *Path(__file__).resolve().parents]
    for env_path in [root / ".env" for root in search_roots]:
        if not env_path.exists():
            continue
        for raw_line in env_path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_dotenv()


def env(name: str, default: str | None = None, *, required: bool = False) -> str:
    value = os.environ.get(name, default)
    if required and not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value or ""


def env_int(name: str, default: int = 0) -> int:
    return int(env(name, str(default)))


def env_float(name: str, default: float = 0.0) -> float:
    return float(env(name, str(default)))


def env_bool(name: str, default: bool = False) -> bool:
    value = env(name, "true" if default else "false").lower()
    return value in {"1", "true", "yes", "y", "on"}


def env_list(name: str, default: str = "") -> list[str]:
    value = env(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def pubkey(name: str, default: str | None = None, *, required: bool = True) -> Pubkey:
    return Pubkey.from_string(env(name, default, required=required))


def keypair(name: str = "SOLANA_ACTIVE_PRIVATE_KEY_BASE58") -> Keypair:
    return Keypair.from_bytes(base58.b58decode(env(name, required=True)))


def client() -> Client:
    return Client(env("SOLANA_RPC_URL", "https://api.devnet.solana.com"))


def print_response(resp) -> None:
    if hasattr(resp, "to_json"):
        print(resp.to_json())
        return
    try:
        print(json.dumps(resp, indent=2, default=str))
    except TypeError:
        print(resp)


def http_get(base_url: str, path: str = "", params: dict | None = None) -> None:
    url = base_url.rstrip("/") + ("/" + path.lstrip("/") if path else "")
    response = requests.get(url, params={k: v for k, v in (params or {}).items() if v not in ("", None)}, timeout=env_int("HTTP_TIMEOUT_SECONDS", 20))
    response.raise_for_status()
    try:
        print_response(response.json())
    except ValueError:
        print(response.text)


def http_post_json(base_url: str, path: str = "", payload: dict | None = None, headers: dict | None = None) -> None:
    url = base_url.rstrip("/") + ("/" + path.lstrip("/") if path else "")
    response = requests.post(url, json=payload or {}, headers=headers or {}, timeout=env_int("HTTP_TIMEOUT_SECONDS", 30))
    response.raise_for_status()
    try:
        print_response(response.json())
    except ValueError:
        print(response.text)


def read_json_file(env_name: str) -> dict:
    return json.loads(Path(env(env_name, required=True)).read_text(encoding="utf-8"))


def send_or_print(instructions, signer_env: str = "SOLANA_ACTIVE_PRIVATE_KEY_BASE58") -> None:
    if not env_bool("SEND_TRANSACTION", False):
        print("DRY RUN: set SEND_TRANSACTION=true to broadcast.")
        for index, instruction in enumerate(instructions, start=1):
            print(f"Instruction {index}: {instruction}")
        return

    from solana.rpc.types import TxOpts
    from solders.message import MessageV0
    from solders.transaction import VersionedTransaction

    payer = keypair(signer_env)
    rpc = client()
    blockhash = rpc.get_latest_blockhash().value.blockhash
    msg = MessageV0.try_compile(
        payer=payer.pubkey(),
        instructions=instructions,
        address_lookup_table_accounts=[],
        recent_blockhash=blockhash,
    )
    tx = VersionedTransaction(msg, [payer])
    print_response(rpc.send_raw_transaction(bytes(tx), opts=TxOpts(skip_preflight=False)))


def main() -> None:
    print_response(client().get_largest_accounts())


if __name__ == "__main__":
    main()
